        "python is awesome"
        "hello world"
        "we are learning python"
        "we will meet tomorrow"

In [1]:
corpus = [
    "python is awesome",
    "hello world",
    "we are learning python",
    "we will meet tomorrow"
]

In [2]:
vocab = []
for document in corpus:
    for word in document.split():
        if word not in vocab:
            vocab.append(word)

In [4]:
vocab

['python',
 'is',
 'awesome',
 'hello',
 'world',
 'we',
 'are',
 'learning',
 'will',
 'meet',
 'tomorrow']

    word to vector

    vector to word

    {'python': 0, 'hello':1}

    {0:'python', 1:'hello'}

In [7]:
vocab = []
for document in corpus:
    for word in document.split():
        if word not in vocab:
            vocab.append(word)
vocab.sort()
vocab

['are',
 'awesome',
 'hello',
 'is',
 'learning',
 'meet',
 'python',
 'tomorrow',
 'we',
 'will',
 'world']

In [8]:
print(vocab)

['are', 'awesome', 'hello', 'is', 'learning', 'meet', 'python', 'tomorrow', 'we', 'will', 'world']

In [9]:
for i in enumerate(vocab):
    print(i)

(0, 'are')
(1, 'awesome')
(2, 'hello')
(3, 'is')
(4, 'learning')
(5, 'meet')
(6, 'python')
(7, 'tomorrow')
(8, 'we')
(9, 'will')
(10, 'world')

In [10]:
print(vocab)

['are', 'awesome', 'hello', 'is', 'learning', 'meet', 'python', 'tomorrow', 'we', 'will', 'world']

In [11]:
v = {w:v for v, w in enumerate(vocab)}

In [12]:
v

{'are': 0,
 'awesome': 1,
 'hello': 2,
 'is': 3,
 'learning': 4,
 'meet': 5,
 'python': 6,
 'tomorrow': 7,
 'we': 8,
 'will': 9,
 'world': 10}

In [13]:
def vocab(corpus):
    vocab = []
    for document in corpus:
        for word in document.split():
            if word not in vocab:
                vocab.append(word)
    vocab.sort()
    v = {w:v for v, w in enumerate(vocab)}
    return v

In [14]:
vocabulary = vocab(corpus)
vocabulary

{'are': 0,
 'awesome': 1,
 'hello': 2,
 'is': 3,
 'learning': 4,
 'meet': 5,
 'python': 6,
 'tomorrow': 7,
 'we': 8,
 'will': 9,
 'world': 10}

In [16]:
corpus

['python is awesome',
 'hello world',
 'we are learning python',
 'we will meet tomorrow']

In [17]:
len(vocabulary)

11

In [18]:
def bag_of_word(corpus, vocabulary):
    vectors = []
    for document in corpus:
        vector = [0] * len(vocabulary)
        for word in document.split():
            if word in vocabulary:
                i = vocabulary[word]
                vector[i] += 1
        vectors.append(vector)
    return vectors

In [19]:
bag_of_word(corpus, vocabulary)

[[0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0]]

In [21]:
df = bag_of_word(corpus, vocabulary)
df

[[0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0]]

In [20]:
import pandas as pd

In [22]:
pd.DataFrame(df, columns=vocabulary.keys())

   are  awesome  hello  is  learning  meet  python  tomorrow  we  will  world
0    0        1      0   1         0     0       1         0   0     0      0
1    0        0      1   0         0     0       0         0   0     0      1
2    1        0      0   0         1     0       1         0   1     0      0
3    0        0      0   0         0     1       0         1   1     1      0

In [17]:
[0] * 10

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [23]:
from sklearn.base import BaseEstimator, TransformerMixin

In [30]:
class Vectorization(BaseEstimator, TransformerMixin):
    def __init__(self):
        self.vocab_ = None
        self.vocab_size_ = None

    def fit(self, corpus):
        vocab = []
        for document in corpus:
            for word in document.split():
                if word not in vocab:
                    vocab.append(word)
        vocab.sort()
        self.vocab_ = {w:v for v, w in enumerate(vocab)}
        self.vocab_size_ = len(self.vocab_)

    def transform(self, corpus):
        vectors = []
        for document in corpus:
            vector = [0] * self.vocab_size_
            for word in document.split():
                if word in self.vocab_:
                    i = self.vocab_[word]
                    vector[i] += 1
            vectors.append(vector)
        return vectors

In [31]:
vectors = Vectorization()

In [32]:
vectors

Vectorization()

In [33]:
vectors.fit(corpus)

In [34]:
vectors.transform(corpus)

[[0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0]]

In [35]:
corpus = [
    "python is awesome awesome awesome",
    "hello world",
    "we are learning python",
    "we will meet tomorrow"
]

In [36]:
vectors.transform(corpus)

[[0, 3, 0, 1, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0]]

In [37]:
vectors.vocab_

{'are': 0,
 'awesome': 1,
 'hello': 2,
 'is': 3,
 'learning': 4,
 'meet': 5,
 'python': 6,
 'tomorrow': 7,
 'we': 8,
 'will': 9,
 'world': 10}

In [38]:
corpus = [
    "python is awesome",
    "hello world",
    "we are learning python",
    "we will meet tomorrow",
    "I am going to jaipur"
]

In [39]:
vectors.transform(corpus)

[[0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [40]:
from sklearn.feature_extraction.text import CountVectorizer

In [41]:
v = CountVectorizer()

In [42]:
v

CountVectorizer()

In [43]:
corpus = [
    "python is awesome",
    "hello world",
    "we are learning python",
    "we will meet tomorrow"
]

In [44]:
v.fit(corpus)

CountVectorizer()

In [45]:
v.vocabulary_

{'python': 6,
 'is': 3,
 'awesome': 1,
 'hello': 2,
 'world': 10,
 'we': 8,
 'are': 0,
 'learning': 4,
 'will': 9,
 'meet': 5,
 'tomorrow': 7}

In [46]:
sp_mx = v.transform(corpus)
sp_mx

<4x11 sparse matrix of type '<class 'numpy.int64'>'
	with 13 stored elements in Compressed Sparse Row format>

In [47]:
sp_mx.toarray()

array([[0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0]], dtype=int64)

    Data Preprocessing: 

                1. Removing Stop words
                2. Removing special char.
                3. Stemming
                4. TF / IDF

In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [26]:
data = pd.read_csv('spam.csv', encoding='latin', usecols=[0, 1])
data.rename({'v1':'label', 'v2':'message'}, axis=1, inplace=True)

In [27]:
data

     label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [28]:
X = data['message']

In [29]:
X = data['message'].str.lower()
X

0       go until jurong point, crazy.. available only ...
1                           ok lar... joking wif u oni...
2       free entry in 2 a wkly comp to win fa cup fina...
3       u dun say so early hor... u c already then say...
4       nah i don't think he goes to usf, he lives aro...
                              ...
5567    this is the 2nd time we have tried 2 contact u...
5568                will ì_ b going to esplanade fr home?
5569    pity, * was in mood for that. so...any other s...
5570    the guy did some bitching but i acted like i'd...
5571                           rofl. its true to its name
Name: message, Length: 5572, dtype: object

In [30]:
y = data['label']
y

0        ham
1        ham
2       spam
3        ham
4        ham
        ...
5567    spam
5568     ham
5569     ham
5570     ham
5571     ham
Name: label, Length: 5572, dtype: object

In [31]:
from sklearn.feature_extraction.text import CountVectorizer

In [32]:
vector = CountVectorizer()
vector.fit(X)
X_tr = vector.transform(X)

In [33]:
X_tr

<5572x8672 sparse matrix of type '<class 'numpy.int64'>'
	with 73916 stored elements in Compressed Sparse Row format>

In [34]:
X_tr.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [35]:
vector.vocabulary_

{'go': 3550,
 'until': 8030,
 'jurong': 4350,
 'point': 5920,
 'crazy': 2327,
 'available': 1303,
 'only': 5537,
 'in': 4087,
 'bugis': 1751,
 'great': 3634,
 'world': 8489,
 'la': 4476,
 'buffet': 1749,
 'cine': 2048,
 'there': 7645,
 'got': 3594,
 'amore': 1069,
 'wat': 8267,
 'ok': 5504,
 'lar': 4512,
 'joking': 4318,
 'wif': 8392,
 'oni': 5533,
 'free': 3358,
 'entry': 2949,
 'wkly': 8447,
 'comp': 2165,
 'to': 7756,
 'win': 8405,
 'fa': 3087,
 'cup': 2386,
 'final': 3207,
 'tkts': 7743,
 '21st': 411,
 'may': 4930,
 '2005': 402,
 'text': 7595,
 '87121': 784,
 'receive': 6297,
 'question': 6190,
 'std': 7230,
 'txt': 7933,
 'rate': 6242,
 'apply': 1156,
 '08452810075over18': 77,
 'dun': 2802,
 'say': 6633,
 'so': 7024,
 'early': 2823,
 'hor': 3927,
 'already': 1042,
 'then': 7640,
 'nah': 5238,
 'don': 2712,
 'think': 7660,
 'he': 3781,
 'goes': 3558,
 'usf': 8075,
 'lives': 4665,
 'around': 1207,
 'here': 3831,
 'though': 7680,
 'freemsg': 3365,
 'hey': 3841,
 'darling': 2443,
 'it': 4218,
 'been': 1460,
 'week': 8313,
 'now': 5420,
 'and': 1084,
 'no': 5367,
 'word': 8480,
 'back': 1351,
 'like': 4615,
 'some': 7039,
 'fun': 3419,
 'you': 8609,
 'up': 8032,
 'for': 3308,
 'still': 7253,
 'tb': 7529,
 'xxx': 8555,
 'chgs': 2002,
 'send': 6723,
 '50': 607,
 'rcv': 6255,
 'even': 2998,
 'my': 5223,
 'brother': 1722,
 'is': 4206,
 'not': 5405,
 'speak': 7112,
 'with': 8433,
 'me': 4939,
 'they': 7653,
 'treat': 7863,
 'aids': 992,
 'patent': 5722,
 'as': 1224,
 'per': 5764,
 'your': 8615,
 'request': 6406,
 'melle': 4969,
 'oru': 5593,
 'minnaminunginte': 5036,
 'nurungu': 5440,
 'vettam': 8131,
 'has': 3757,
 'set': 6750,
 'callertune': 1823,
 'all': 1029,
 'callers': 1822,
 'press': 6041,
 'copy': 2266,
 'friends': 3381,
 'winner': 8416,
 'valued': 8100,
 'network': 5317,
 'customer': 2399,
 'have': 3770,
 'selected': 6709,
 'receivea': 6298,
 '900': 816,
 'prize': 6073,
 'reward': 6461,
 'claim': 2054,
 'call': 1813,
 '09061701461': 224,
 'code': 2120,
 'kl341': 4439,
 'valid': 8096,
 '12': 322,
 'hours': 3947,
 'had': 3699,
 'mobile': 5089,
 '11': 312,
 'months': 5129,
 'or': 5570,
 'more': 5133,
 'entitled': 2946,
 'update': 8037,
 'the': 7627,
 'latest': 4526,
 'colour': 2141,
 'mobiles': 5090,
 'camera': 1835,
 'co': 2109,
 'on': 5525,
 '08002986030': 61,
 'gonna': 3574,
 'be': 1438,
 'home': 3901,
 'soon': 7066,
 'want': 8245,
 'talk': 7496,
 'about': 859,
 'this': 7669,
 'stuff': 7320,
 'anymore': 1123,
 'tonight': 7792,
 've': 8115,
 'cried': 2344,
 'enough': 2936,
 'today': 7763,
 'six': 6928,
 'chances': 1943,
 'cash': 1889,
 'from': 3397,
 '100': 298,
 '20': 397,
 '000': 1,
 'pounds': 5982,
 'csh11': 2363,
 '87575': 789,
 'cost': 2278,
 '150p': 351,
 'day': 2458,
 '6days': 680,
 '16': 363,
 'tsandcs': 7898,
 'reply': 6399,
 'hl': 3873,
 'info': 4122,
 'urgent': 8055,
 'won': 8464,
 'membership': 4975,
 'our': 5606,
 'jackpot': 4247,
 '81010': 737,
 'www': 8537,
 'dbuk': 2463,
 'net': 5311,
 'lccltd': 4543,
 'pobox': 5899,
 '4403ldnw1a7rw18': 559,
 'searching': 6678,
 'right': 6473,
 'words': 8481,
 'thank': 7612,
 'breather': 1691,
 'promise': 6105,
 'wont': 8471,
 'take': 7488,
 'help': 3817,
 'granted': 3623,
 'will': 8402,
 'fulfil': 3415,
 'wonderful': 8468,
 'blessing': 1567,
 'at': 1260,
 'times': 7722,
 'date': 2451,
 'sunday': 7388,
 'xxxmobilemovieclub': 8556,
 'use': 8069,
 'credit': 2334,
 'click': 2077,
 'wap': 8250,
 'link': 4637,
 'next': 5334,
 'message': 4993,
 'http': 3968,
 'com': 2144,
 'qjkgighjjgcbl': 6182,
 'oh': 5499,
 'watching': 8272,
 'eh': 2870,
 'remember': 6366,
 'how': 3953,
 'spell': 7127,
 'his': 3864,
 'name': 5244,
 'yes': 8592,
 'did': 2592,
 'naughty': 5271,
 'make': 4848,
 'wet': 8350,
 'fine': 3215,
 'if': 4041,
 'thatåõs': 7625,
 'way': 8284,
 'feel': 3158,
 'its': 4225,
 'gota': 3595,
 'england': 2927,
 'macedonia': 4810,
 'dont': 2716,
 'miss': 5052,
 'goals': 3554,
 'team': 7541,
 'news': 5330,
 'ur': 8051,
 'national': 5265,
 '87077': 783,
 'eg': 2865,
 'try': 7894,
 'wales': 8225,
 'scotland': 6657,
 '4txt': 599,
 'ì¼1': 8659,
 'poboxox36504w45wq': 5911,
 'that': 7621,
 'seriously': 6743,
 'going': 3563,
 'ha': 3695,
 'ì_': 8658,
 'pay': 5734,
 'first': 3232,
 'when': 8362,
 'da': 2416,
 'stock': 7256,
 'comin': 2155,
 'aft': 962,
 'finish': 3218,
 'lunch': 4776,
 'str': 7281,
 'down': 2737,
 'lor': 4719,
 'ard': 1182,
 'smth': 7007,
 'ffffffffff': 3177,
 'alright': 1043,
 'can': 1839,
 'meet': 4958,
 'sooner': 7067,
 'just': 4352,
 'forced': 3310,
 'myself': 5228,
 'eat': 2835,
 'slice': 6959,
 'really': 6280,
 'hungry': 3988,
 'tho': 7676,
 'sucks': 7357,
 'mark': 4885,
 'getting': 3511,
 'worried': 8492,
 'knows': 4450,
 'sick': 6877,
 'turn': 7917,
 'pizza': 5854,
 'lol': 4696,
 'always': 1052,
 'convincing': 2254,
 'catch': 1899,
 'bus': 1771,
 'are': 1183,
 'frying': 3403,
 'an': 1079,
 'egg': 2867,
 'tea': 7535,
 'eating': 2838,
 'mom': 5110,
 'left': 4566,
 'over': 5627,
 'dinner': 2624,
 'do': 2675,
 'love': 4740,
 'amp': 1071,
 'we': 8289,
 're': 6259,
 'packing': 5653,
 'car': 1861,
 'll': 4669,
 'let': 4587,
 'know': 4447,
 'room': 6514,
 'ahhh': 987,
 'work': 8482,
 'vaguely': 8092,
 'what': 8355,
 'does': 2687,
 'wait': 8219,
 'clear': 2071,
 'were': 8339,
 'sure': 7414,
 'being': 1478,
 'sarcastic': 6613,
 'why': 8385,
 'doesn': 2689,
 'live': 4661,
 'us': 8065,
 'yeah': 8580,
 'was': 8259,
 'apologetic': 1143,
 'fallen': 3112,
 'out': 5609,
 'she': 6795,
 'actin': 904,
 'spoilt': 7154,
 'child': 2010,
 'caught': 1903,
 'till': 7719,
 'but': 1778,
 'doing': 2702,
 'too': 7796,
 'badly': 1356,
 'cheers': 1986,
 'tell': 7559,
 'anything': 1129,
 'fear': 3150,
 'of': 5477,
 'fainting': 3104,
 'housework': 3951,
 'quick': 6193,
 'cuppa': 2388,
 'thanks': 7613,
 'subscription': 7345,
 'ringtone': 6482,
 'uk': 7963,
 'charged': 1955,
 'month': 5126,
 'please': 5879,
 'confirm': 2209,
 'by': 1794,
 'replying': 6400,
 'yup': 8637,
 'look': 4707,
 'timings': 7726,
 'msg': 5168,
 'again': 970,
 'xuhui': 8551,
 'learn': 4556,
 '2nd': 461,
 'her': 3830,
 'lesson': 4585,
 '8am': 809,
 'oops': 5548,
 'roommate': 6516,
 'done': 2714,
 'see': 6695,
 'letter': 4589,
 'decide': 2481,
 'hello': 3814,
 'saturday': 6625,
 'texting': 7603,
 'decided': 2482,
 'tomo': 7781,
 'trying': 7896,
 'invite': 4180,
 'pls': 5887,
 'ahead': 986,
 'watts': 8280,
 'wanted': 8247,
 'weekend': 8315,
 'abiola': 855,
 'forget': 3316,
 'need': 5291,
 'crave': 2324,
 'most': 5141,
 'sweet': 7445,
 'arabian': 1179,
 'steed': 7237,
 'mmmmmm': 5079,
 'yummy': 8632,
 '07732584351': 30,
 'rodger': 6504,
 'burns': 1768,
 'tried': 7872,
 'sms': 7002,
 'nokia': 5377,
 'camcorder': 1833,
 '08000930705': 57,
 'delivery': 2521,
 'tomorrow': 7783,
 'who': 8378,
 'seeing': 6697,
 'hope': 3919,
 'man': 4858,
 'well': 8330,
 'endowed': 2917,
 'am': 1054,
 'lt': 4763,
 'gt': 3663,
 'inches': 4091,
 'calls': 1828,
 'messages': 4995,
 'missed': 5054,
 'didn': 2594,
 'get': 3503,
 'hep': 3829,
 'immunisation': 4070,
 'nigeria': 5344,
 'fair': 3105,
 'hopefully': 3922,
 'tyler': 7946,
 'could': 2289,
 'maybe': 4932,
 'ask': 1234,
 'bit': 1544,
 'stubborn': 7309,
 'hospital': 3934,
 'kept': 4396,
 'telling': 7560,
 'weak': 8290,
 'sucker': 7355,
 'hospitals': 3935,
 'suckers': 7356,
 'thinked': 7661,
 'time': 7721,
 'saw': 6632,
 'class': 2063,
 'gram': 3615,
 'usually': 8081,
 'runs': 6557,
 'half': 3711,
 'eighth': 2873,
 'smarter': 6982,
 'gets': 3507,
 'almost': 1038,
 'whole': 8379,
 'second': 6682,
 'fyi': 3435,
 'ride': 6472,
 'morning': 5137,
 'crashing': 2323,
 'place': 5856,
 'wow': 8508,
 'never': 5321,
 'realized': 6278,
 'embarassed': 2898,
 'accomodations': 886,
 'thought': 7681,
 'liked': 4616,
 'since': 6902,
 'best': 1498,
 'seemed': 6701,
 'happy': 3746,
 'cave': 1907,
 'sorry': 7076,
 'give': 3532,
 'offered': 5484,
 'embarassing': 2899,
 'ac': 872,
 'sptv': 7176,
 'new': 5325,
 'jersey': 4288,
 'devils': 2573,
 'detroit': 2567,
 'red': 6320,
 'wings': 8414,
 'play': 5870,
 'ice': 4022,
 'hockey': 3886,
 'correct': 2271,
 'incorrect': 4102,
 'end': 2913,
 'mallika': 4857,
 'sherawat': 6802,
 'yesterday': 8594,
 'find': 3212,
 'url': 8061,
 'congrats': 2215,
 'year': 8581,
 'special': 7114,
 'cinema': 2049,
 'pass': 5711,
 'yours': 8619,
 '09061209465': 219,
 'suprman': 7412,
 'matrix3': 4918,
 'starwars3': 7218,
 'etc': 2986,
 'bx420': 1792,
 'ip4': 4189,
 '5we': 641,
 '150pm': 353,
 'later': 4525,
 'meeting': 4960,
 'where': 8366,
 'reached': 6262,
 'gauti': 3469,
 'sehwag': 6706,
 'odi': 5476,
 'series': 6741,
 'pick': 5826,
 'burger': 1763,
 'yourself': 8620,
 'move': 5154,
 'pain': 5660,
 'killing': 4421,
 'good': 3576,
 'joke': 4314,
 'girls': 3529,
 'situation': 6925,
 'seekers': 6698,
 'part': 5700,
 'checking': 1980,
 'iq': 4195,
 'roommates': 6517,
 'took': 7797,
 'forever': 3313,
 'come': 2150,
 'double': 2730,
 'check': 1976,
 'hair': 3706,
 'dresser': 2760,
 'said': 6583,
 'wun': 8536,
 'cut': 2403,
 'short': 6837,
 'nice': 5338,
 'pleased': 5880,
 'advise': 945,
 'following': 3291,
 'recent': 6301,
 'review': 6459,
 'mob': 5087,
 'awarded': 1320,
 '1500': 350,
 'bonus': 1608,
 '09066364589': 267,
 'song': 7061,
 'dedicated': 2492,
 'which': 8372,
 'dedicate': 2491,
 'valuable': 8098,
 'frnds': 3389,
 'rply': 6533,
 'complimentary': 2184,
 'trip': 7873,
 'eurodisinc': 2992,
 'trav': 7855,
 'aco': 900,
 'entry41': 2950,
 '1000': 299,
 'dis': 2636,
 '18': 368,
 'morefrmmob': 5134,
 'shracomorsglsuplt': 6862,
 '10': 297,
 'ls1': 4759,
 '3aj': 518,
 'hear': 3793,
 'divorce': 2665,
 'barbie': 1387,
 'comes': 2152,
 'ken': 4394,
 'plane': 5862,
 'wah': 8212,
 'lucky': 4770,
 'save': 6628,
 'money': 5117,
 'hee': 3806,
 'finished': 3220,
 'hi': 3846,
 'babe': 1342,
 'im': 4058,
 'wanna': 8243,
 'something': 7049,
 'xx': 8552,
 'performed': 5771,
 'waiting': 8222,
 'machan': 4812,
 'once': 5529,
 'thats': 7624,
 'cool': 2259,
 'gentleman': 3494,
 'dignity': 2614,
 'respect': 6426,
 'peoples': 5763,
 'very': 8130,
 'much': 5186,
 'shy': 6872,
 'pa': 5649,
 'operate': 5555,
 'after': 963,
 'same': 6598,
 'looking': 4711,
 'job': 4303,
 'ta': 7473,
 'earn': 2824,
 'ah': 984,
 'stop': 7266,
 'urgnt': 8058,
 'real': 6271,
 'yo': 8604,
 'tickets': 7709,
 'one': 5531,
 'jacket': 4246,
 'used': 8070,
 'multis': 5195,
 'started': 7213,
 'requests': 6407,
 'came': 1834,
 'bed': 1455,
 'coins': 2126,
 'factory': 3094,
 'gotta': 3600,
 'nitros': 5362,
 'ela': 2878,
 'kano': 4375,
 'il': 4053,
 'download': 2738,
 'wen': 8333,
 'stand': 7201,
 'close': 2084,
 'another': 1106,
 'night': 5346,
 'spent': 7132,
 'late': 4522,
 'afternoon': 965,
 'casualty': 1897,
 'means': 4946,
 'haven': 3771,
 'any': 1120,
 'stuff42moro': 7321,
 'includes': 4095,
 'sheets': 6797,
 'smile': 6990,
 'pleasure': 5882,
 'trouble': 7880,
 'pours': 5984,
 'rain': 6216,
 'sum1': 7379,
 'hurts': 3998,
 'becoz': 1453,
 'someone': 7043,
 'loves': 4748,
 'smiling': 6994,
 'service': 6746,
 'representative': 6404,
 '0800': 53,
 '169': 366,
 '6031': 647,
 'between': 1507,
 '10am': 307,
 '9pm': 835,
 'guaranteed': 3666,
 '5000': 609,
 'havent': 3772,
 'planning': 5866,
 'buy': 1783,
 'lido': 4600,
 '530': 627,
 'show': 6853,
 'collected': 2135,
 'simply': 6899,
 'password': 5718,
 'mix': 5070,
 '85069': 770,
 'verify': 8126,
 'usher': 8076,
 'britney': 1712,
 'fml': 3282,
 'telugu': 7565,
 'movie': 5157,
 'abt': 867,
 'loads': 4675,
 'loans': 4677,
 'wk': 8443,
 'hols': 3899,
 'run': 6555,
 'forgot': 3321,
 'hairdressers': 3708,
 'appointment': 1159,
 'four': 3339,
 'shower': 6855,
 'beforehand': 1467,
 'cause': 1904,
 'prob': 6078,
 'ham': 3717,
 'nothing': 5410,
 'else': 2892,
 'okay': 5505,
 'price': 6054,
 'long': 4703,
 'legal': 4569,
 'them': 7636,
 'ave': 1307,
 'ams': 1075,
 'gone': 3572,
 '4the': 597,
 'driving': 2769,
 'test': 7589,
 'yet': 8595,
 'mean': 4942,
 'guess': 3672,
 'gave': 3470,
 'boston': 1629,
 'men': 4979,
 'changed': 1945,
 'search': 6677,
 'location': 4680,
 'nyc': 5451,
 'cuz': 2410,
 'signin': 6887,
 'page': 5656,
 'says': 6636,
 'umma': 7970,
 'life': 4603,
 'vava': 8112,
 'lot': 4727,
 'dear': 2471,
 'wishes': 8427,
 'birthday': 1542,
 'making': 4852,
 'truly': 7889,
 'memorable': 4976,
 'aight': 994,
 'hit': 3866,
 'would': 8504,
 'ip': 4188,
 'address': 922,
 'considering': 2227,
 'computer': 2190,
 'isn': 4213,
 'minecraft': 5030,
 'server': 6745,
 'grumpy': 3660,
 'old': 5517,
 'people': 5762,
 'better': 1504,
 'lying': 4790,
 'jokes': 4316,
 'worry': 8494,
 'busy': 1777,
 'plural': 5891,
 'noun': 5417,
 'research': 6412,
 'cos': 2276,
 'things': 7659,
 'scared': 6642,
 'mah': 4835,
 'loud': 4735,
 'gent': 3492,
 'contact': 2232,
 'last': 4519,
 'weekends': 8316,
 'draw': 2752,
 'shows': 6861,
 '09064012160': 243,
 'k52': 4358,
 '12hrs': 333,
 '150ppm': 355,
 'wa': 8207,
 'openin': 5552,
 'sentence': 6734,
 'formal': 3325,
 'anyway': 1132,
 'juz': 4357,
 'tt': 7904,
 'eatin': 2837,
 'puttin': 6171,
 'weight': 8321,
 'haha': 3702,
 'anythin': 1128,
 'happened': 3738,
 'entered': 2939,
 'cabin': 1801,
 'boss': 1628,
 'felt': 3167,
 'askd': 1235,
 'invited': 4181,
 'apartment': 1137,
 'went': 8336,
 'specially': 7118,
 'holiday': 3896,
 'flights': 3258,
 'inc': 4089,
 'operator': 5556,
 '0871277810910p': 129,
 'min': 5023,
 'goodo': 3585,
 'must': 5214,
 'friday': 3376,
 'potato': 5976,
 'ratio': 6245,
 'tortilla': 7814,
 'needed': 5293,
 'hmm': 3878,
 'uncle': 7979,
 'informed': 4125,
 'paying': 5739,
 'school': 6648,
 'directly': 2630,
 'food': 3298,
 'private': 6070,
 '2004': 401,
 'account': 889,
 'statement': 7221,
 '07742676969': 32,
 '786': 709,
 'unredeemed': 8023,
 'points': 5921,
 '08719180248': 175,
 'identifier': 4034,
 '45239': 570,
 'expires': 3065,
 '2000': 399,
 'caller': 1821,
 '03': 15,
 'landline': 4499,
 '09064019788': 249,
 'box42wr29c': 1655,
 'apples': 1154,
 'pairs': 5664,
 'malarky': 4854,
 'todays': 7764,
 'voda': 8176,
 'numbers': 5437,
 'ending': 2915,
 '7548': 701,
 '350': 506,
 'award': 1319,
 'match': 4906,
 '08712300220': 111,
 'quoting': 6204,
 '4041': 543,
 'standard': 7202,
 'rates': 6243,
 'app': 1147,
 'sao': 6607,
 'mu': 5184,
 'ìï': 8661,
 'predict': 6016,
 'buying': 1786,
 'yetunde': 8597,
 'hasn': 3759,
 'sent': 6733,
 'bother': 1632,
 'sending': 6725,
 'involve': 4185,
 'shouldn': 6848,
 'imposed': 4077,
 'apologise': 1144,
 'girl': 3526,
 'del': 2511,
 'bak': 1364,
 'sum': 7378,
 'lucyxx': 4773,
 'tmorrow': 7749,
 'accomodate': 885,
 'answer': 1109,
 'sunshine': 7395,
 'quiz': 6200,
 'top': 7805,
 'sony': 7063,
 'dvd': 2812,
 'player': 5872,
 'country': 2296,
 'algarve': 1022,
 'ansr': 1108,
 '82277': 744,
 'sp': 7099,
 'tyrone': 7950,
 'laid': 4491,
 'dogging': 2696,
 'locations': 4681,
 'direct': 2629,
 'join': 4311,
 'largest': 4516,
 'bt': 1738,
 'txting': 7939,
 'gravel': 3628,
 '69888': 675,
 'nt': 5427,
 'ec2a': 2840,
 '31p': 498,
 'haf': 3701,
 'msn': 5175,
 'yijue': 8601,
 'hotmail': 3942,
 'him': 3857,
 'rooms': 6518,
 'befor': 1465,
 'activities': 910,
 'msgs': 5174,
 'chat': 1966,
 'svc': 7430,
 'hardcore': 3748,
 'services': 6747,
 '69988': 679,
 'age': 973,
 'yr': 8627,
 'lazy': 4542,
 'type': 7947,
 'lect': 4563,
 'pouch': 5979,
 'sir': 6914,
 'mail': 4840,
 'swt': 7459,
 'nver': 5445,
 'tired': 7729,
 'little': 4660,
 'lovable': 4739,
 'persons': 5789,
 'coz': 2309,
 'somtimes': 7058,
 'those': 7677,
 'occupy': 5469,
 'biggest': 1524,
 'their': 7633,
 'hearts': 3799,
 'gud': 3668,
 'ni8': 5336,
 'open': 5549,
 'ya': 8565,
 'dot': 2729,
 'whats': 8357,
 'staff': 7193,
 'taking': 7493,
 'replied': 6397,
 'randy': 6236,
 'sexy': 6763,
 'female': 3168,
 'local': 4679,
 'luv': 4781,
 'netcollex': 5312,
 'ltd': 4764,
 '08700621170150p': 81,
 'ummma': 7972,
 'begin': 1471,
 'qatar': 6177,
 'pray': 6011,
 'hard': 3747,
 'deleted': 2515,
 'sindu': 6904,
 'birla': 1538,
 'soft': 7029,
 'wine': 8412,
 'flowing': 3273,
 'nevering': 5322,
 'thk': 7670,
 'plaza': 5877,
 'typical': 7949,
 'everywhere': 3016,
 'dirt': 2633,
 'floor': 3267,
 'windows': 8409,
 'shirt': 6816,
 'sometimes': 7051,
 'mouth': 5153,
 'dream': 2755,
 'without': 8437,
 'chores': 2037,
 'joy': 4329,
 'lots': 4729,
 'tv': 7922,
 'exist': 3050,
 ...}

In [36]:
from sklearn.naive_bayes import MultinomialNB

In [38]:
model = MultinomialNB()
model.fit(X_tr, y)
y_hat = model.predict(X_tr)

In [39]:
y_hat

array(['ham', 'ham', 'spam', ..., 'ham', 'ham', 'ham'], dtype='<U4')

In [40]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [41]:
print(f"Accuracy Score: {accuracy_score(y, y_hat)}")

Accuracy Score: 0.9935391241923905

In [53]:
y

0        ham
1        ham
2       spam
3        ham
4        ham
        ...
5567    spam
5568     ham
5569     ham
5570     ham
5571     ham
Name: label, Length: 5572, dtype: object

In [54]:
y.value_counts()

label
ham     4825
spam     747
Name: count, dtype: int64

In [42]:
print(f"Confusion matrix:\n {confusion_matrix(y, y_hat)}")

Confusion matrix:
 [[4812   13]
 [  23  724]]

In [56]:
from sklearn.model_selection import StratifiedShuffleSplit

In [57]:
split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=123)

In [58]:
(train_idx, test_idx), = split.split(X, y)

In [59]:
train_idx

array([4128,  134, 2360, ..., 4344, 3697, 3389], dtype=int64)

In [60]:
test_idx

array([4574, 2858, 2515, ..., 3891,  436, 1953], dtype=int64)

In [61]:
X_train = X[train_idx]
X_test = X[test_idx]
y_train = y[train_idx]
y_test = y[test_idx]

In [62]:
from sklearn.pipeline import Pipeline

In [63]:
model = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('classification', MultinomialNB())
])

In [64]:
model.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()),
                ('classification', MultinomialNB())])

In [65]:
y_hat_train = model.predict(X_train)
y_hat_test = model.predict(X_test)

In [66]:
y_hat_train

array(['ham', 'spam', 'ham', ..., 'ham', 'ham', 'spam'], dtype='<U4')

In [67]:
y_hat_test

array(['ham', 'ham', 'ham', ..., 'spam', 'ham', 'ham'], dtype='<U4')

In [68]:
def evaluate(y, y_hat):
    print(f"Accuracy Score: {accuracy_score(y, y_hat):.2f}\n")
    print(f"Confusion Matrix:\n {confusion_matrix(y, y_hat)}\n")
    print(f"Classification Report:\n {classification_report(y, y_hat)} ")

In [69]:
evaluate(y_train, y_hat_train)

Accuracy Score: 0.99

Confusion Matrix:
 [[3852    7]
 [  17  581]]

Classification Report:
               precision    recall  f1-score   support

         ham       1.00      1.00      1.00      3859
        spam       0.99      0.97      0.98       598

    accuracy                           0.99      4457
   macro avg       0.99      0.98      0.99      4457
weighted avg       0.99      0.99      0.99      4457

In [70]:
y_train.value_counts()

label
ham     3859
spam     598
Name: count, dtype: int64

In [71]:
evaluate(y_test, y_hat_test)

Accuracy Score: 0.99

Confusion Matrix:
 [[961   5]
 [ 10 139]]

Classification Report:
               precision    recall  f1-score   support

         ham       0.99      0.99      0.99       966
        spam       0.97      0.93      0.95       149

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115